- name: Install stuff into ec2 hosts
  hosts: 34.232.65.207
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ~/ansible.pem
  become: yes

  roles:
    - server
    - php
    - mysql
    - wordpress
